import { AnimatePresence, motion } from 'framer-motion';
import { AlertTriangle, Info, Loader2, RefreshCw, Trash2, Unlink } from 'lucide-react';
import type { UserEdital } from '@/utils/editaisPagePresentation';

type EditaisConfirmDialogsProps = {
    deleteConfirm: { isOpen: boolean; edital: UserEdital | null };
    unloadConfirm: { isOpen: boolean; edital: UserEdital | null };
    processingId: string | null;
    onCloseDelete: () => void;
    onDelete: () => void;
    onCloseUnload: () => void;
    onUnload: () => Promise<void>;
};

export function EditaisConfirmDialogs({ deleteConfirm, unloadConfirm, processingId, onCloseDelete, onDelete, onCloseUnload, onUnload }: EditaisConfirmDialogsProps) {
    const deleting = deleteConfirm.edital?.id === processingId;
    const unloading = unloadConfirm.edital?.id === processingId;
    return <>
        <AnimatePresence>{deleteConfirm.isOpen && deleteConfirm.edital && <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4"><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onCloseDelete} className="absolute inset-0 bg-black/60 backdrop-blur-sm" /><motion.div initial={{ opacity: 0, scale: .95, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: .95, y: 20 }} className="relative flex w-full max-w-md flex-col gap-6 rounded-[32px] border border-border bg-modal p-8 text-modal-foreground shadow-2xl dark:border-white/[0.08]"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-destructive/10"><Trash2 className="text-destructive" size={28} /></div><div><h3 className="text-xl font-bold tracking-tight text-foreground">Excluir Edital?</h3><p className="mt-0.5 text-xs font-medium text-content-muted">Esta ação afetará suas matérias e progresso.</p></div></div><div className="text-sm leading-relaxed text-content-muted"><p className="mb-4">Tem certeza que deseja excluir o edital <strong>&quot;{deleteConfirm.edital.name}&quot;</strong>?</p><div className={`rounded-xl border p-4 text-sm ${deleteConfirm.edital.isImported ? 'border-primary/20 bg-primary/10 text-primary' : 'border-destructive/30 bg-destructive/10 text-destructive'}`}><div className="flex items-start gap-3">{deleteConfirm.edital.isImported ? <Info size={18} className="mt-0.5 shrink-0" /> : <AlertTriangle size={18} className="mt-0.5 shrink-0" />}<div><p className="mb-1 text-[10px] font-bold uppercase tracking-widest">{deleteConfirm.edital.isImported ? 'Edital Importado' : 'Criação Manual'}</p><p className="leading-normal opacity-90">{deleteConfirm.edital.isImported ? <>Este edital foi importado. Se você excluí-lo, poderá <strong>adicioná-lo novamente</strong> da biblioteca sem perda de dados históricos.</> : <>Este edital foi criado manualmente. A exclusão é <strong>permanente</strong> e todos os registros vinculados serão removidos.</>}</p></div></div></div></div><div className="mt-2 flex gap-3"><button onClick={onCloseDelete} disabled={deleting} className="app-button-secondary flex-1 py-4 text-xs font-bold uppercase tracking-widest">Cancelar</button><button onClick={onDelete} disabled={deleting} className="app-button-danger flex flex-1 items-center justify-center gap-2 py-4 text-xs font-bold uppercase tracking-widest">{deleting ? <RefreshCw size={16} className="animate-spin" /> : <Trash2 size={16} />}Confirmar</button></div></motion.div></div>}</AnimatePresence>
        <AnimatePresence>{unloadConfirm.isOpen && unloadConfirm.edital && <div className="fixed inset-0 z-[100] flex items-center justify-center p-4"><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => !unloading && onCloseUnload()} className="absolute inset-0 bg-black/60 backdrop-blur-sm" /><motion.div initial={{ opacity: 0, scale: .95 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .95 }} role="alertdialog" aria-modal="true" aria-labelledby="unload-cycle-title" className="relative w-full max-w-md rounded-[32px] border border-border bg-modal p-8 text-modal-foreground shadow-2xl dark:border-white/[0.08]"><div className="mb-6 flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-warning/10"><Unlink className="text-warning" size={22} /></div><div><h3 id="unload-cycle-title" className="text-base font-semibold tracking-tight text-content-main">Remover edital do ciclo?</h3><p className="mt-0.5 text-xs text-content-muted">As matérias deste edital sairão da fila atual de estudos.</p></div></div><div className="mb-8 text-sm leading-relaxed text-content-muted">Tem certeza que deseja remover o edital <strong>&quot;{unloadConfirm.edital.name}&quot;</strong> do seu ciclo atual?<div className="mt-4 rounded-xl border border-primary/20 bg-primary/10 p-4 text-sm text-primary"><div className="flex items-start gap-3"><Info size={18} className="mt-0.5 shrink-0" /><div><p className="font-bold">Informação importante:</p><p className="mt-1 opacity-90">Seu progresso, sessões de estudo e histórico de revisões <strong>não serão perdidos</strong>. As revisões ficam pausadas fora do ciclo e serão retomadas quando você carregar este edital novamente.</p></div></div></div></div><div className="grid grid-cols-2 gap-3"><button type="button" autoFocus onClick={onCloseUnload} disabled={unloading} className="app-button-secondary flex min-h-11 items-center justify-center px-4 text-xs font-bold uppercase tracking-widest">Cancelar</button><button type="button" onClick={onUnload} disabled={unloading} className="app-button-warning flex min-h-11 items-center justify-center gap-2 px-4 text-xs font-bold uppercase tracking-widest">{unloading ? <><Loader2 size={16} className="animate-spin" />Removendo</> : 'Remover'}</button></div></motion.div></div>}</AnimatePresence>
    </>;
}
