
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { resolveSupabaseEnv } from './env';

const { url: SUPABASE_URL, publishableKey: SUPABASE_PUBLISHABLE_KEY } = resolveSupabaseEnv({
  env: import.meta.env,
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    // AuthCallback and ResetPassword process callback credentials explicitly.
    detectSessionInUrl: false,
    // The SPA must support confirmation links opened from a different browser
    // or device than the one that started signup.
    flowType: 'implicit'
  }
});
