
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { resolveSupabaseEnv } from './env';
import {
  getSupabaseAuthStorageKey,
  preserveSessionForBillingPortalReturn,
  restoreSessionAfterBillingPortalReturn,
} from './portalSessionRecovery';

const { url: SUPABASE_URL, publishableKey: SUPABASE_PUBLISHABLE_KEY } = resolveSupabaseEnv({
  env: import.meta.env,
});
const authStorageKey = getSupabaseAuthStorageKey(SUPABASE_URL);

// This must happen before createClient reads its persisted INITIAL_SESSION.
restoreSessionAfterBillingPortalReturn(authStorageKey);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: authStorageKey,
    persistSession: true,
    autoRefreshToken: true,
    // AuthCallback and ResetPassword process callback credentials explicitly.
    detectSessionInUrl: false,
    // The SPA must support confirmation links opened from a different browser
    // or device than the one that started signup.
    flowType: 'implicit'
  }
});

export const preserveStripePortalSessionForReturn = () =>
  preserveSessionForBillingPortalReturn(authStorageKey);
